# Linear Algebra



## Basic manipulation of matrices:

In [0]:
import numpy as np

In [0]:
#To create matrices:
l = [[1,2,3],[1,2,3],[2,3,4]]
a = np.array(l, dtype = int)
print(a)
print(a.shape)

[[1 2 3]
 [1 2 3]
 [2 3 4]]
(3, 3)


In [0]:
#Or to create special matrices:
print(np.zeros((3,3,3)))
print(np.ones((2,5)))
print(np.eye(4))
print(np.full((3,3),3))

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[3 3 3]
 [3 3 3]
 [3 3 3]]


In [0]:
#Random:
#Uniform distribution [0,1)
print(np.random.random((2,3)))

#Uniform in [k,b)
k = 12
b = 14
print(k+ (b-k)*(np.random.random((2,3))))

#integers: [l,h),sz
print(np.random.randint(1,3,(3,3)))

#Normal distribution:
#(mean, std, dim)
print(np.random.normal(2,3,(2,3)))


[[0.31456061 0.37693734 0.70573696]
 [0.08024172 0.51335    0.50331112]]
[[13.38663092 13.73106154 12.6083846 ]
 [13.13158881 13.78203405 12.70770313]]
[[1 1 2]
 [1 1 1]
 [1 2 2]]
[[0.5631315  1.09335317 2.29320022]
 [5.22062624 2.4076147  2.13536915]]


In [0]:
#Operations:
print(a+a)
print(a-2*a)
print(a+3)
#This give us the product by entry
print(a*a)

#This give us the product as matrix:
a = np.random.random((3,3))
b = np.random.random((3,3))
np.matmul(a,b)

[[0.41456491 1.02989098 1.57358371]
 [1.24740595 0.5316745  1.33736328]
 [0.01239793 0.27562631 1.30282601]]
[[-0.20728246 -0.51494549 -0.78679186]
 [-0.62370297 -0.26583725 -0.66868164]
 [-0.00619897 -0.13781316 -0.651413  ]]
[[3.20728246 3.51494549 3.78679186]
 [3.62370297 3.26583725 3.66868164]
 [3.00619897 3.13781316 3.651413  ]]
[[4.29660172e-02 2.65168856e-01 6.19041425e-01]
 [3.89005399e-01 7.06694425e-02 4.47135136e-01]
 [3.84271853e-05 1.89924662e-02 4.24338902e-01]]


array([[1.15341484, 1.21884754, 0.31248669],
       [0.43950244, 0.74036674, 0.12662094],
       [0.77557651, 1.67070317, 0.86708922]])

In [0]:
#Most of the time, you will run into trouble if you multiply
#a np row by a matrix, so use instead: np.dot(a,b)
a = np.random.random((3,3))
b = np.random.random((3))
np.matmul(a,b) #which is the same as a@b

array([0.41446679, 0.76876242, 0.63051487])

In [0]:
#Access a position:
print(a[1,2])
print(a[1][2])

0.009262022016930604
0.009262022016930604


In [0]:
#Access multiple positions:
print(a[:,2])
print(a[2,:])

[0.23115098 0.00926202 0.90260273]
[0.02731712 0.97960475 0.90260273]


In [0]:
#Also, we can select the positions:
print(a[[0,2],:])

[[0.96433292 0.32798834 0.23115098]
 [0.02731712 0.97960475 0.90260273]]


## Solve linear systems: 

In [0]:
#Determinant:
np.linalg.det(a)

0.554924751963129

In [0]:
#solve a linear system:
a = np.random.random((3,3))
b = np.random.random((3,1))

x = np.linalg.solve(a,b)
print(x)

[[ 17.52278575]
 [ 48.51687754]
 [-48.3292995 ]]


In [0]:
#Make sure:
print(np.matmul(a,x))
print(b)

[[0.56521365]
 [0.94397658]
 [0.1029123 ]]
[[0.56521365]
 [0.94397658]
 [0.1029123 ]]


In [0]:
#Alternative:
ainv = np.linalg.inv(a)
#It is recommended to use np.linalg.pinv(a)
#You will discover why in future lessons
xalt = np.matmul(ainv,b)
print(xalt)

[[ 17.52278575]
 [ 48.51687754]
 [-48.3292995 ]]


In [0]:
#transpose:
np.transpose(b)

array([[0.56521365, 0.94397658, 0.1029123 ]])

## Constants and distribution of data:

In [0]:
# np.arange(low,top[,inc)

np.arange(1,5,2)

array([1, 3])

In [4]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [0]:
np.pi, np.inf

(3.141592653589793, inf)